#! /bin/sh

if [ ! "$1" ]; then
  echo "*** Version number missing ***"
  exit 1
fi

case $1 in pmw-*) echo "*** Just give the version number ***"; exit 1;; esac

# These files are detrailed.

files="\
  configure.ac \
  README \
  LICENCE \
  INSTALL \
  src/*.c \
  src/*.h \
  src/config.h.in \
  src/README \
  doc/ChangeLog \
  doc/pmw.1"

echo Detrailing
perl ./Detrail $files
if [ $? -ne 0 ] ; then
  echo "** Detrailing failed"
  exit 1
fi

dir=Releases/pmw-$1
mkdir $dir

echo "Created directory $dir"

# Single files

cp INSTALL LICENCE NOTICE README Makefile.in PSheader MIDIvoices MIDIperc configure configure.ac install-sh mkinstalldirs post-install $dir

# Whole directories

cp -r contrib fontmetrics macros testdist $dir

# Source

mkdir $dir/src
cp src/Makefile src/*.c src/*.h src/*.in $dir/src

# Fonts

mkdir $dir/psfonts
cp psfonts/PMW-Music.pfa psfonts/PMW-Alpha $dir/psfonts

# Documentation

mkdir $dir/doc
cp doc/spec.pdf   $dir/doc
cp doc/pmw.1      $dir/doc
cp doc/ChangeLog  $dir/doc
cp doc/Cygwin.txt $dir/doc
cp doc/MacOS.txt  $dir/doc

# Add additional files for developer use and distributions that require the
# documentation sources.

cp doc/Makefile  $dir/doc
cp doc/spec.xfpt $dir/doc

mkdir $dir/doc/examples
mkdir $dir/doc/figures
mkdir $dir/doc/postscript
cp doc/examples/* $dir/doc/examples
cp doc/figures/*  $dir/doc/figures

# Tar and compress

pushd Releases
tar cf pmw-$1.tar pmw-$1
gzip -v --best pmw-$1.tar
echo Releases/pmw-$1.tar.gz created

####
